#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import webbrowser
import time
x=r"https://jitm.ut.ac.ir/article_57818.html"
for i in range(100):
    time.sleep(2)
    webbrowser.open(x)
    print(i)
print('finish')